name: Security audit

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Use latest version of checkout
      - uses: taiki-e/install-action@v1 # Use latest stable tag
        with:
          tool: cargo-deny # Specify the tool to install
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
